# @package _global_

defaults:
  - _self_
  - /server: local
  - /experiment: difficult_gaussian
  - /method: dds

run_name: ${hydra:job.override_dirname}
group: ${task}
seed: 0

num_steps: 16
sigma: 1.0
alpha: 0.1
tf: 1.0

log_every_n_epochs: 100