# @package _global_

defaults:
  - _self_
  - /server: local
  - /experiment: difficult_gaussian
  - /method: dds

run_name: ${hydra:job.override_dirname}
group: ${task}
seed: 0

steps_mult: 1
sigma: 1.0
alpha: 1.0
tf: 1.0

epochs: 10000
log_every_n_epochs: 100
save_samples: False