# @package _global_

defaults:
  - _self_
  - server: local

run_name: ${hydra:job.override_dirname}
experiment: 'difficult_gaussian'
group: ${experiment}
seed: 0

use_vi_approx: True

tf: 6.4
num_steps: 128
sigma: 1.0
alpha: 0.6875

step_scheme: cos_sq

log_every_n_epochs: 100